# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 22:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='possession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posse', models.CharField(default='属地', max_length=20)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='单位')),
            ],
            options={
                'verbose_name': '属地分配',
                'verbose_name_plural': '属地分配',
            },
        ),
        migrations.CreateModel(
            name='userguid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devicetype', models.CharField(choices=[('pr', '打印机'), ('com', '计算机')], default='com', max_length=6)),
                ('Configinfo', models.CharField(max_length=300, verbose_name='配置信息')),
                ('ipaddress', models.CharField(max_length=100, verbose_name='ip地址')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用人姓名')),
            ],
            options={
                'verbose_name': '员工信息设备',
                'verbose_name_plural': '员工信息设备',
            },
        ),
    ]
