# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userguid', '0002_auto_20171016_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possession',
            name='posse',
            field=models.CharField(choices=[('jg', '机关大楼'), ('dd', '调度楼'), ('xq', '西区'), ('dq', '东区'), ('bq', '北区'), ('nq', '南区')], max_length=2, verbose_name='属地'),
        ),
        migrations.AlterField(
            model_name='possession',
            name='unit',
            field=models.CharField(max_length=20, verbose_name='单位'),
        ),
    ]
