# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userguid',
            name='username',
        ),
        migrations.DeleteModel(
            name='Userguid',
        ),
    ]
