# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 21:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soname', models.CharField(max_length=100, verbose_name='故障标题')),
                ('desc', models.CharField(max_length=300, verbose_name='故障描述')),
                ('solu', models.CharField(max_length=300, verbose_name='解决办法')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '常见故障',
                'verbose_name_plural': '常见故障',
            },
        ),
        migrations.CreateModel(
            name='solutionResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download', models.FileField(upload_to='solution/resource/%Y/%m', verbose_name='资源文件')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('soname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solutions.solution', verbose_name='故障名')),
            ],
            options={
                'verbose_name': '课程资源',
                'verbose_name_plural': '课程资源',
            },
        ),
    ]
