# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 23:18
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workorders', '0001_initial'),
        ('userguid', '0002_auto_20171016_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='employs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userguid.userguid', verbose_name='设备id')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userguid.possession', verbose_name='所在单位')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='员工姓名')),
            ],
            options={
                'verbose_name': '员工设备',
                'verbose_name_plural': '员工设备',
            },
        ),
        migrations.CreateModel(
            name='ordComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=0, verbose_name='接收用户')),
                ('comments', models.CharField(max_length=500, verbose_name='评论')),
                ('has_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('ordernum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workorders.workord', verbose_name='工单号')),
            ],
            options={
                'verbose_name': '工单讨论',
                'verbose_name_plural': '工单讨论',
            },
        ),
    ]
